# Generated by Django 4.1.6 on 2023-04-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('age', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('tel', models.CharField(max_length=30)),
                ('sexo', models.CharField(choices=[('F', 'Female'), ('M', 'Man')], max_length=1)),
            ],
        ),
    ]
